worldName: example-world-name
serverName: example-server-name
password: password 

resources: {}

storage:
  kind: hostvol
  hostvol:
    path: /data/valheim
  pvc:
    storageClassName: default
    size: 1Gi

networking:
  serviceType: LoadBalancer

nodeSelector: {}
