apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
spec:
  selector:
    matchLabels:
      app: valheim-server
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: lloesche/valheim-server:latest
        name: vailheim-server
        env:
        - name: SERVER_NAME
          value: {{ .Values.serverName }}
        - name: WORLD_NAME
          value: {{ .Values.worldName }}
        - name: SERVER_PASS
          value: {{ .Values.password }}
        ports:
        - containerPort: 2456
          name: game1
        - containerPort: 2457
          name: game2
        - containerPort: 2458
          name: game3
        {{ if eq .Values.storage.kind "hostvol" }}
        volumeMounts:
        - mountPath: /config
          name: gamefiles
        {{ end }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
      {{ if eq .Values.storage.kind "hostvol" }}
      volumes:
      - name: gamefiles
        hostPath:
          path: {{ .Values.storage.hostvol.path }}
          type: Directory
      {{ end }}

