# Source: valheim-k8s/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
spec:
  selector:
    matchLabels:
      app: valheim-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - image: "lloesche/valheim-server:latest"
        name: valheim-server
        env:
        - name: SERVER_NAME
          value: example-server-name
        - name: WORLD_NAME
          value: example-world-name
        - name: SERVER_PASS
          value: password
        - name: SERVER_PORT
          value: "2456"
        ports:
        - containerPort: 2456
          name: gameport
        - containerPort: 2457
          name: queryport
        volumeMounts:
        
        - mountPath: /config
          name: gamefiles
        
        
        resources:
          {}
      volumes:
      
      - name: gamefiles
        hostPath:
          path: /data/valheim
          type: DirectoryOrCreate
