# Source: valheim-k8s/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: valheim-server
spec:
  ports:
  - name: gameport
    port: 2456
    targetPort: 2456
    protocol: UDP
  
  - name: queryport
    port: 2457
    targetPort: 2457
    protocol: UDP
  
  type: LoadBalancer
  selector:
    app: valheim-server
