apiVersion: v1
kind: Service
metadata:
  name: valheim-server
spec:
  ports:
  - name: game1
    port: 2456
    targetPort: 2456
    protocol: UDP
  - name: game2
    port: 2457
    targetPort: 2457
    protocol: UDP
  - name: game3
    port: 2458
    targetPort: 2458
    protocol: UDP
  type: LoadBalancer
  selector:
    app: valheim-server
